/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cadastros;

import javax.swing.JOptionPane;
import main.Main;
import repositorio.*;

/**
 *
 * @author Aluno
 */
public class Tela_inicial extends javax.swing.JFrame {

    /**
     * Creates new form Tela_inicial
     */
    public Tela_inicial() {
        initComponents();
        int QuantidadeClientes, QuantidadeFuncionarios, QuantidadeEstoque, QuantidadeItens, QuantidadePedidos;
        
        QuantidadeFuncionarios = new Rep().quantidade("funcionarios");
        QuantidadeClientes = new Rep().quantidade("clientes");
        QuantidadePedidos = new Rep().quantidade("pedidos");
        QuantidadeEstoque = new Rep().quantidade("estoque");
        QuantidadeItens = new Rep().quantidade("itens");
        
        jLabelFuncionarioTotal.setText(Integer.toString(QuantidadeFuncionarios));
        jLabelClientestotal.setText(Integer.toString(QuantidadeClientes));
        jLabelPedidosTotal.setText(Integer.toString(QuantidadePedidos));
        jLabelEstoqueTotal.setText(Integer.toString(QuantidadeEstoque));
        jLabelItemTotal.setText(Integer.toString(QuantidadeItens));
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabelEstoqueIcon = new javax.swing.JLabel();
        jLabelEstoqueTotal = new javax.swing.JLabel();
        jLabelEstoque = new javax.swing.JLabel();
        panel6 = new java.awt.Panel();
        jLabelClientesIcon = new javax.swing.JLabel();
        jLabelClientestotal = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        panel7 = new java.awt.Panel();
        jLabePedidosIcon = new javax.swing.JLabel();
        jLabelPedidosTotal = new javax.swing.JLabel();
        jLabelPedidos = new javax.swing.JLabel();
        panel10 = new java.awt.Panel();
        jLabelItemIcon = new javax.swing.JLabel();
        jLabelItemTotal = new javax.swing.JLabel();
        jLabelItem = new javax.swing.JLabel();
        panel13 = new java.awt.Panel();
        jLabelFuncioarioIcon = new javax.swing.JLabel();
        jLabelFuncionarioTotal = new javax.swing.JLabel();
        jLabelFuncionario = new javax.swing.JLabel();
        jMenuBarNavegacao = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemFuncionario = new javax.swing.JMenuItem();
        jMenuOperacional = new javax.swing.JMenu();
        jMenuItemItem = new javax.swing.JMenuItem();
        jMenuItemPedido = new javax.swing.JMenuItem();
        jMenuItemEstoque = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Principal_icon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Delicatessen");

        panel1.setBackground(new java.awt.Color(102, 102, 102));
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel1MouseClicked(evt);
            }
        });

        jLabelEstoqueIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Estoque_icon.png"))); // NOI18N

        jLabelEstoqueTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEstoqueTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstoqueTotal.setText("000");

        jLabelEstoque.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstoque.setText("Estoque");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabelEstoqueIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEstoqueTotal)
                .addGap(30, 30, 30))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelEstoque)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabelEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEstoqueIcon)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelEstoqueTotal)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panel6.setBackground(new java.awt.Color(102, 102, 102));
        panel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel6MouseClicked(evt);
            }
        });

        jLabelClientesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pessoa_icon.png"))); // NOI18N

        jLabelClientestotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelClientestotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClientestotal.setText("000");

        jLabelClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelClientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClientes.setText("Clientes");

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabelClientesIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClientestotal)
                .addGap(30, 30, 30))
            .addGroup(panel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelClientesIcon)
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelClientestotal)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panel7.setBackground(new java.awt.Color(102, 102, 102));
        panel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel7MouseClicked(evt);
            }
        });

        jLabePedidosIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pedidos_icon.png"))); // NOI18N

        jLabelPedidosTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPedidosTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPedidosTotal.setText("000");

        jLabelPedidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPedidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPedidos.setText("Pedidos");

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabePedidosIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPedidosTotal)
                .addGap(30, 30, 30))
            .addGroup(panel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelPedidos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabePedidosIcon)
                    .addGroup(panel7Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelPedidosTotal)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panel10.setBackground(new java.awt.Color(102, 102, 102));
        panel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel10MouseClicked(evt);
            }
        });

        jLabelItemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Item_icon.png"))); // NOI18N

        jLabelItemTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelItemTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelItemTotal.setText("000");

        jLabelItem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelItem.setForeground(new java.awt.Color(255, 255, 255));
        jLabelItem.setText("item");

        javax.swing.GroupLayout panel10Layout = new javax.swing.GroupLayout(panel10);
        panel10.setLayout(panel10Layout);
        panel10Layout.setHorizontalGroup(
            panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel10Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabelItemIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelItemTotal)
                .addGap(30, 30, 30))
            .addGroup(panel10Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabelItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel10Layout.setVerticalGroup(
            panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel10Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabelItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelItemIcon)
                    .addGroup(panel10Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelItemTotal)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panel13.setBackground(new java.awt.Color(102, 102, 102));
        panel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel13MouseClicked(evt);
            }
        });

        jLabelFuncioarioIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Funcionario_icon.png"))); // NOI18N

        jLabelFuncionarioTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelFuncionarioTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFuncionarioTotal.setText("000");

        jLabelFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFuncionario.setText("Funcionario");

        javax.swing.GroupLayout panel13Layout = new javax.swing.GroupLayout(panel13);
        panel13.setLayout(panel13Layout);
        panel13Layout.setHorizontalGroup(
            panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel13Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFuncionario)
                    .addGroup(panel13Layout.createSequentialGroup()
                        .addComponent(jLabelFuncioarioIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFuncionarioTotal)))
                .addGap(16, 16, 16))
        );
        panel13Layout.setVerticalGroup(
            panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFuncioarioIcon)
                    .addGroup(panel13Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelFuncionarioTotal)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jMenuCadastros.setText("Cadastros");

        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCliente);

        jMenuItemFuncionario.setText("Funcionario");
        jMenuItemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionarioActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemFuncionario);

        jMenuBarNavegacao.add(jMenuCadastros);

        jMenuOperacional.setText("Operacional");

        jMenuItemItem.setText("Item");
        jMenuItemItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemItemActionPerformed(evt);
            }
        });
        jMenuOperacional.add(jMenuItemItem);

        jMenuItemPedido.setText("Agendar Pedido");
        jMenuItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPedidoActionPerformed(evt);
            }
        });
        jMenuOperacional.add(jMenuItemPedido);

        jMenuItemEstoque.setText("Adicionar ao estoque");
        jMenuItemEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstoqueActionPerformed(evt);
            }
        });
        jMenuOperacional.add(jMenuItemEstoque);

        jMenuBarNavegacao.add(jMenuOperacional);

        setJMenuBar(jMenuBarNavegacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(panel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionarioActionPerformed
        this.dispose();
        new Funcionario().setVisible(true);
    }//GEN-LAST:event_jMenuItemFuncionarioActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        this.dispose();
        new Cliente().setVisible(true);
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemItemActionPerformed
        this.dispose();
        new Item().setVisible(true);
    }//GEN-LAST:event_jMenuItemItemActionPerformed

    private void jMenuItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPedidoActionPerformed
        this.dispose();
        new Pedido().setVisible(true);
    }//GEN-LAST:event_jMenuItemPedidoActionPerformed

    private void jMenuItemEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstoqueActionPerformed
        this.dispose();
        new Estoque().setVisible(true);
    }//GEN-LAST:event_jMenuItemEstoqueActionPerformed

    private void panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseClicked
        // Estoque
        this.dispose();
        new Estoque().setVisible(true);
    }//GEN-LAST:event_panel1MouseClicked

    private void panel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel6MouseClicked
        //Cliente
        this.dispose();
        new Cliente().setVisible(true);
       
    }//GEN-LAST:event_panel6MouseClicked

    private void panel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel10MouseClicked
        // Item
        this.dispose();
        new Item().setVisible(true);
    }//GEN-LAST:event_panel10MouseClicked

    private void panel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel13MouseClicked
        // Funcionario
        this.dispose();
        new Funcionario().setVisible(true);
    }//GEN-LAST:event_panel13MouseClicked

    private void panel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel7MouseClicked
        // Pedidos
        this.dispose();
        new Pedido().setVisible(true);
    }//GEN-LAST:event_panel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_inicial().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabePedidosIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelClientesIcon;
    private javax.swing.JLabel jLabelClientestotal;
    private javax.swing.JLabel jLabelEstoque;
    private javax.swing.JLabel jLabelEstoqueIcon;
    private javax.swing.JLabel jLabelEstoqueTotal;
    private javax.swing.JLabel jLabelFuncioarioIcon;
    private javax.swing.JLabel jLabelFuncionario;
    private javax.swing.JLabel jLabelFuncionarioTotal;
    private javax.swing.JLabel jLabelItem;
    private javax.swing.JLabel jLabelItemIcon;
    private javax.swing.JLabel jLabelItemTotal;
    private javax.swing.JLabel jLabelPedidos;
    private javax.swing.JLabel jLabelPedidosTotal;
    private javax.swing.JMenuBar jMenuBarNavegacao;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemEstoque;
    private javax.swing.JMenuItem jMenuItemFuncionario;
    private javax.swing.JMenuItem jMenuItemItem;
    private javax.swing.JMenuItem jMenuItemPedido;
    private javax.swing.JMenu jMenuOperacional;
    private java.awt.Panel panel1;
    private java.awt.Panel panel10;
    private java.awt.Panel panel13;
    private java.awt.Panel panel6;
    private java.awt.Panel panel7;
    // End of variables declaration//GEN-END:variables
}
